config/routes.rb
Rails.application.routes.draw do
  # TODO: remove routes /users/cancel and /users/edit
  devise_for :users

  devise_scope :user do
    namespace :admin do
      resources :users
      resources :decks
      resources :entries
      resources :rates
    end

    controller 'home' do
      get 'practice'
      post 'quick_preview'
      post 'rate'
      patch 'remote_update'
      # TODO: Change to patch
      get 'generate_api_key'
      get 'export'

    end

    root 'home#index'
  end
end

app/controllers/home_controller.rb
require 'csv'

class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:export]

  def index
    @decks = current_user.decks.order(created_at: :desc)
    t = Time.now.at_end_of_day
    @rates_by_dates = 7.times.map do |i|
      [
        (t - i.day).to_date,
        (0..3).map{ |i| [i, 0] }.to_h.merge(
          current_user.rates.where(created_at: (t - (i + 1).day)..(t - i.day))
          .to_a.group_by(&:value).transform_values(&:length)
        )
      ]
    end
  end

  def quick_preview
    video_id_or_url = params[:quick_review].require(:video_id_or_url)
    # TODO: Implement default language setting UI
    deck = Deck.new_for_quick_preview(video_id_or_url, 'ru', 'en')
    deck.user = current_user
    if deck.save
      redirect_to practice_path(deck_id: deck.id)
    else
      redirect_to root_path, alert: 'Quick preview failed.'
    end
  end

  def practice
    if params[:deck_id] && params[:entry_id]
      @deck = current_user.decks.find(params[:deck_id])
      @rate_entry = @deck.entries.find(params[:entry_id])
      @seq_mode = params[:seq_mode]
    else
      decks = current_user.decks.where(practice_mode: true)
      if decks.length == 0
        return redirect_to(root_path, alert: 'Please select decks to practice.')
      else
        @deck = decks.sample
        @rate_entry = @deck.get_entry_for_practice
      end
    end
    @practice_info = {
      video_id: @deck.video_id,
      begin_sec: @rate_entry ? @rate_entry.begin_sec : 0,
      # TODO: when "autoplay: false, loop: true", it does autoplay video.
      autoplay: current_user.autoplay,
      loop: current_user.loop,
    }
  end

  def rate
    entry = current_user.entries.find(params[:rate][:entry_id])
    if entry.rates.create(value: params[:rate][:value])
      if params[:seq_mode]
        deck = entry.deck
        next_entry = deck.next_entry(entry)
        redirect_to practice_path(deck_id: deck.id, entry_id: next_entry.id, seq_mode: params[:seq_mode])
      else
        redirect_to practice_path
      end
    else
      head :bad_request
    end
  end

  def remote_update
    klass = Object.const_get(params.require(:model).camelcase)
    attrs = params.require(klass.model_name.singular).permit(:id, :loop, :autoplay, :practice_mode)
    @model = klass.find(attrs[:id])
    authorize @model, :update?
    @model.update(attrs)
    respond_to :js
  end

  def generate_api_key
    current_user.generate_api_key
    current_user.save!
    redirect_to :root
  end

  def export
    if user = User.where(id: params[:id], api_key: params[:api_key]).first
      case params[:type]
      when 'decks'
        output = CSV.generate(col_sep: "\t") do |csv|
          user.decks.each do |deck|
            csv << [deck.id, deck.name, deck.video_id]
          end
        end
        render plain: output
      when 'rates'
        output = CSV.generate(col_sep: "\t") do |csv|
          user.rates.includes(:deck).each do |rate|
            csv << [rate.entry.deck.id, rate.entry.id, rate.value, rate.created_at]
          end
        end
        render plain: output
      else
        head :bad_request
      end
    else
      head :unauthorized
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_deck_form.html.erb
<%= form_for model,
      url: remote_update_path(model: 'deck', partial: 'deck_form', swap_id: "deck-form-#{model.id}"),
      remote: true,
      html: { id: "deck-form-#{model.id}" } do |f| %>
  <%= f.hidden_field :id %>
  <%= f.check_box :practice_mode, onclick: 'Rails.fire(this.parentElement, "submit")' %>
<% end %>

app/views/home/_settings.html.erb
<div>
  <div>Loop</div>
  <%= form_for model,
        url: remote_update_path(model: 'user', partial: 'settings', swap_id: 'settings-form'),
        remote: true,
        html: { id: 'settings-form' } do |f| %>
    <%= f.hidden_field :id %>
    <%= f.check_box :loop, onclick: 'Rails.fire(this.parentElement, "submit")' %>
  <% end %>
</div>
<div>
  <div>Autoplay</div>
  <%= form_for model,
        url: remote_update_path(model: 'user', partial: 'settings', swap_id: 'settings-form'),
        remote: true,
        html: { id: 'settings-form' } do |f| %>
    <%= f.hidden_field :id %>
    <%= f.check_box :autoplay, onclick: 'Rails.fire(this.parentElement, "submit")' %>
  <% end %>
</div>

app/views/home/index.html.erb
<div id='overlay'>
  <div id='remote-update-notice'>Update Successful</div>
</div>
<div id='home'>
  <section>
    <h2>Menu</h2>
    <ul>
      <li><%= link_to 'Start practice', practice_path %></li>
      <li><%= link_to 'Create new deck', [:new, :admin, :deck] %></li>
      <li><%= link_to 'Browse all data', admin_decks_path(deck: { direction: :desc, order: :created_at }) %></li>
      <li><%= link_to 'Recent Practice', admin_rates_path(rate: { direction: :desc, order: :created_at }) %></li>
      <li><%= link_to 'Sign out', destroy_session_path(:user), method: :delete %></li>
    </ul>
  </section>
  <section>
    <h2>Quick Preview</h2>
    <div id='quick-preview-body'>
      <%= form_for :quick_review, url: quick_preview_path do |f| %>
        <%= f.text_field :video_id_or_url, placeholder: "Video ID or URL" %>
        <%= f.button 'Go', value: 'go' %>
      <% end %>
    </div>
  </section>
  <section>
    <h2>Settings</h2>
    <div id='settings-body'>
      <%= render partial: 'settings', locals: { model: current_user } %>
    </div>
  </section>
  <section>
    <h2>Decks</h2>
    <div id='decks-table-container'>
      <div class='table'>
        <div class='table__header'>
          <div>Name (Practice)</div>
          <div>0</div>
          <div>1</div>
          <div>2</div>
          <div>3</div>
          <div>?</div>
          <div>Total</div>
        </div>
        <div class='table__body'>
          <!-- TODO: Should cache deck.get_stats -->
          <% @decks.each do |deck| %>
            <div>
              <% h = deck.get_stats %>
              <div><%= link_to deck.name,
                          practice_path(deck_id: deck.id,
                                        entry_id: deck.ordered_entries.first.id,
                                        seq_mode: true) %></div>
              <div>
                <%= render partial: 'deck_form', locals: { model: deck } %>
              </div>
              <div>
                <a id='download' target='_blank' href='<%= "https://youtube-dl-service.herokuapp.com/download?video=#{deck.video_id}" %>'>
                  <i class="material-icons">get_app</i>
                </a>
              </div>
              <div><%= h[0] %></div>
              <div><%= h[1] %></div>
              <div><%= h[2] %></div>
              <div><%= h[3] %></div>
              <div><%= h[nil] %></div>
              <div><%= deck.entries.length %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <section>
    <h2>Practice log</h2>
    <div id='practice-log-table-container'>
      <div class='table'>
        <div class='table__header'>
          <div>Date</div>
          <div>0</div>
          <div>1</div>
          <div>2</div>
          <div>3</div>
          <div>Total</div>
        </div>
        <div class='table__body'>
          <% @rates_by_dates.each do |date, h| %>
            <div>
              <div><%= date %></div>
              <div><%= h[0] %></div>
              <div><%= h[1] %></div>
              <div><%= h[2] %></div>
              <div><%= h[3] %></div>
              <div><%= h[0] + h[1] + h[2] + h[3] %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <section>
    <h2>CSV Export Links</h2>
    <ul>
      <% attrs = current_user.attributes.slice('id', 'api_key') %>
      <li><%= link_to "Decks", export_url(attrs.merge(type: 'decks')) %></li>
      <li><%= link_to "Rates", export_url(attrs.merge(type: 'rates')) %></li>
      <li><%= link_to "Regenerate API key", generate_api_key_path %></li>
    </ul>
  </section>
</div>

app/views/home/practice.html.erb
<div id="app">
  <div id="player-container">
    <div id="player-aspect-ratio-fixer1">
      <div id="player-aspect-ratio-fixer2">
        <div id="player-iframe"></div>
      </div>
    </div>
  </div>
  <div id="subtitle-container">
    <!-- double click on mobile won't work? -->
    <% @deck.ordered_entries.each do |entry| %>
      <div
        class="entry"
        onclick="togglePlayEntry(this)"
        data-id="<%= entry.id %>"
        data-begin_sec="<%= entry.begin_sec %>"
        data-end_sec="<%= entry.end_sec %>"
        data-rate="<%= @rate_entry && entry.id == @rate_entry.id %>"
        data-play=""
        data-paused=""
        data-loop=""
      >
        <div class="entry__header">
          <div class="log">
            <% entry.rates.each do |rate| %>
              <div><%= rate.value %></div>
            <% end %>
          </div>
          <div class="time"><%= entry.begin_slim %> - <%= entry.end_slim %></div>
          <div class="rate">
            <%= link_to practice_path(deck_id: @deck.id, entry_id: entry.id, seq_mode: @seq_mode) do %>
              <i class="material-icons">edit</i>
            <% end %>
          </div>
          <div class="loop">
            <i class="material-icons" onclick="event.stopPropagation(); toggleLoopingEntry(this.closest('.entry'))">repeat</i>
          </div>
          <div class="play">
            <i class="material-icons" onclick="togglePlayEntry(this.closest('.entry'))">play_circle_outline</i>
          </div>
        </div>
        <div class="entry__body">
          <div><%= entry.text1 %></div>
          <div><%= entry.text2 %></div>
        </div>
      </div>
    <% end %>
  </div>
  <div id="nav">
    <%= link_to 'Home', root_path %>
    <% [0, 1, 2, 3].each do |v| %>
      <div onclick='this.firstElementChild.submit()'>
        <%= form_for @rate_entry.rates.new(value: v),
                      url: rate_path(seq_mode: @seq_mode) do |f| %>
          <%= f.hidden_field :entry_id %>
          <%= f.hidden_field :value %>
          <%= v %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<script>

// Globals
var G_player;
var G_iframe;
var G_rateEntry;
var G_loopingEntries;
var G_interval;
var G_practice_info = <%= raw @practice_info.to_json %>;

class Player {
  constructor() {
    this.apiReadyP = null; this.readyP = null;
    this.apiReady = false; this.ready = false;
    this.player = null;
    this.initializeApi();
  }
  initializeApi() {
    this.apiReadyP = new Promise(resolve => {
      window.onYouTubeIframeAPIReady = () => {
        this.apiReady = true;
        resolve(window.YT);
      }
    });
  }
  initializeIframe(node, options) {
    this.readyP = new Promise(resolve => {
      this.apiReadyP.then(YT => {
        this.YT = YT;
        options = Object.assign({}, options, {
          events: {
            onReady: () => {
              this.ready = true;
              resolve();
            }
          }
        });
        this.player = new this.YT.Player(node, options);
      });
    });
  }
  seekTo(sec) {
    this.player.seekTo(sec);
  }
  getCurrentTime() {
    return this.player.getCurrentTime();
  }
  isPaused() {
    return this.player.getPlayerState() == 2;
  }
  pauseVideo() {
    this.player.pauseVideo();
  }
  playVideo() {
    this.player.playVideo();
  }
}

function init() {
  G_player = new Player;
  G_iframe = document.querySelector('#player-iframe');
  G_rateEntry = document.querySelector('.entry[data-rate="true"]');
  G_loopingEntries = G_rateEntry && G_practice_info.loop ? [G_rateEntry] : [];
};

function main() {
  if (G_rateEntry) { scrollToEntry(G_rateEntry) };
  G_player.initializeIframe(G_iframe, {
    videoId: G_practice_info.video_id,
    height: '480', width: '853',
    playerVars: {
      autoplay: G_practice_info.autoplay ? '1' : '0',
      start: G_practice_info.begin_sec
    },
  });
  G_player.readyP.then(() => {
    G_interval = window.setInterval(() => {
      // Reset style
      Array.from(document.querySelectorAll('.entry')).forEach(n => {
        n.setAttribute('data-play', '');
        n.setAttribute('data-paused', '');
        n.setAttribute('data-loop', '');
      })

      // Set new playing entry
      var time = G_player.getCurrentTime();
      var currentEntry = findCurrentEntry(time);
      if (currentEntry) {
        currentEntry.setAttribute(G_player.isPaused() ? 'data-paused' : 'data-play', 'true');
      }

      // Loop entry
      if (G_loopingEntries.length > 0) {
        G_loopingEntries.map(n => n.setAttribute('data-loop', 'true'));
        var b = _.min(G_loopingEntries.map(n => Number(n.getAttribute('data-begin_sec'))));
        var e = _.max(G_loopingEntries.map(n => Number(n.getAttribute('data-end_sec'))));
        if (time < b || e < time) {
          G_player.seekTo(b);
        }
      }
    }, 250);
  });
}

function findCurrentEntry(time) {
  var nodes = Array.from(document.querySelectorAll('.entry')).reverse();
  var node = nodes.find(n => {
    var b = Number(n.getAttribute('data-begin_sec'));
    var e = Number(n.getAttribute('data-end_sec'));
    return b <= time;
  });
  return node;
}

function togglePlayEntry(node) {
  if (!G_loopingEntries.includes(node)) {
    G_loopingEntries = [];
  }
  var time = G_player.getCurrentTime();
  var currentEntry = findCurrentEntry(time);
  if (node == currentEntry) {
    if (G_player.isPaused()) {
      G_player.playVideo();
    } else {
      G_player.pauseVideo();
    }
  } else {
    var entryTime = Number(node.getAttribute('data-begin_sec'));
    G_player.seekTo(entryTime);
    G_player.playVideo();
  }
}

function toggleLoopingEntry(node) {
  if (G_loopingEntries.includes(node)) {
    G_loopingEntries = G_loopingEntries.filter(n => n !== node);
  } else {
    G_loopingEntries.push(node);
  }
}

function setRateEntry(node) {

}

function scrollToEntry(entry) {
  entry.parentNode.scrollTop =
    entry.offsetTop
    - entry.parentNode.offsetTop
    - entry.parentNode.offsetHeight / 2
    + entry.offsetHeight / 2;
}

init();
document.addEventListener('DOMContentLoaded', function() {
  main();
});

</script>
<script type="text/javascript" async="" src="https://www.youtube.com/iframe_api"></script>

app/views/home/remote_update.js.erb
var notice = document.querySelector("#remote-update-notice");
notice.className = '';
// NOTE: for some browser, timeout 0 doesn't trigger animation.
window.setTimeout(() => notice.className = 'show', 10);

document.querySelector("#<%= params[:swap_id] %>").innterHTML =
  "<%= j (render partial: params[:partial], locals: { model: @model }) %>";